server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/ #配置Nacos地址

service-url:
  nacos-user-service: http://nacos-payment-provider
